FROM alpine:latest AS builder

RUN apk add --no-cache \
    gcc \
    make \
    musl-dev

WORKDIR /app
COPY inc/ inc/
COPY src/ src/
COPY Makefile .
RUN make

FROM alpine:latest
COPY --from=builder /app/bin/server /usr/local/bin/server
EXPOSE 80

CMD ["server"]